name: CI/CD - Simple Auth API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Rodar testes da API
        run: mvn -B -q test

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

  allure-report:
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
      - name: Baixar Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Gerar Allure Report
        run: |
          curl -sLo allure.tgz https://repo1.maven.org/maven2/io/qameta/allure/allure-commandline/2.27.0/allure-commandline-2.27.0.tgz
          tar -xzf allure.tgz
          ./allure-2.27.0/bin/allure generate allure-results -o allure-report --clean
          echo "Report gerado em allure-report"

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy-prod:
    runs-on: ubuntu-latest
    needs: allure-report
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build JAR (sem testes)
        run: mvn -B -q -DskipTests package

      - name: Encontrar JAR
        id: jar
        run: |
          FILE=$(ls target/*.jar | head -n1)
          echo "file=$FILE" >> $GITHUB_OUTPUT
          echo "JAR localizado: $FILE"

      - name: Upload do JAR (Deploy Simulado)
        uses: actions/upload-artifact@v4
        with:
          name: simple-auth-jar
          path: ${{ steps.jar.outputs.file }}
          retention-days: 15
