name: CI/CD - Simple Auth API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: com.login.william
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run UNIT tests (@Tag unit)
        run: mvn -q -B clean test -Djunit.jupiter.tags=unit

      - name: Upload Allure results (UNIT)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-unit
          path: com.login.william/target/allure-results
          if-no-files-found: error

  api-tests:
    runs-on: ubuntu-latest
    needs: unit-tests   # <<<<<< faz o unit rodar ANTES
    defaults:
      run:
        working-directory: com.login.william
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run API tests (@Tag api)
        run: mvn -q -B clean test -Djunit.jupiter.tags=api

      - name: Upload Allure results (API)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-api
          path: com.login.william/target/allure-results
          if-no-files-found: error

  allure-report:
    runs-on: ubuntu-latest
    needs: [unit-tests, api-tests]
    steps:
      - uses: actions/checkout@v4

      - name: Download Allure results (UNIT)
        uses: actions/download-artifact@v4
        with:
          name: allure-results-unit
          path: results/unit

      - name: Download Allure results (API)
        uses: actions/download-artifact@v4
        with:
          name: allure-results-api
          path: results/api

      - name: Merge results
        run: |
          mkdir -p results/merged
          cp -R results/unit/* results/merged/ 2>/dev/null || true
          cp -R results/api/*  results/merged/ 2>/dev/null || true
          echo "Merged files:"
          find results/merged -type f | sed 's/^/ - /'
          test -n "$(ls -A results/merged)" || (echo "No Allure results" && exit 1)

      - name: Download Allure CLI
        run: |
          curl -sLo allure.tgz https://repo1.maven.org/maven2/io/qameta/allure/allure-commandline/2.27.0/allure-commandline-2.27.0.tgz
          tar -xzf allure.tgz

      - name: Generate Allure Report
        run: ./allure-2.27.0/bin/allure generate results/merged -o allure-report --clean

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy-pages:
    runs-on: ubuntu-latest
    needs: allure-report
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download Allure report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
