name: CI/CD - Simple Auth API

on:
  push:
  pull_request:

jobs:
  build:
    name: build (compilar sem testes)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build (skip tests)
        run: mvn -q -B -U clean package -DskipTests

      - name: Publicar artefatos (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: |
            **/target/*.jar
          if-no-files-found: warn

  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Se você usa @Tag("unit") no JUnit 5:
      - name: Testes unitários (somente @unit)
        run: mvn -q -B test -Dgroups=unit -DskipITs=true

      - name: Allure results (unit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-unit
          path: |
            **/target/allure-results/**
            **/target/surefire-reports/**
          if-no-files-found: warn

  api-tests:
    name: api-tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Exemplo: rodar só @api (Rest Assured)
      - name: Testes de API (@api)
        run: mvn -q -B test -Dgroups=api

      - name: Allure results (api)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-api
          path: |
            **/target/allure-results/**
            **/target/surefire-reports/**
          if-no-files-found: warn

  allure-report:
    name: allure-report
    runs-on: ubuntu-latest
    needs: [unit-tests, api-tests]
    steps:
      - uses: actions/checkout@v4

      - name: Baixar resultados Allure
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Unificar results
        run: |
          mkdir -p target/allure-results
          find artifacts -type d -name "allure-results" -exec cp -r {}/* target/allure-results/ \; || true

      - name: Gerar relatório Allure estático
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: target/allure-results
          allure_report: target/allure-report

      - name: Publicar relatório como artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

  deploy-pages:
    name: deploy-pages
    runs-on: ubuntu-latest
    needs: allure-report
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./site
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
