name: CI/CD - Simple Auth API

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: com.login.william

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build (skip tests)
        run: mvn -q -B -U clean package -DskipTests
      - name: Publicar JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: com.login.william/**/target/*.jar
          if-no-files-found: warn

  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Testes unitários (@unit)
        run: mvn -q -B test -Dgroups=unit -DskipITs=true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-unit
          path: |
            com.login.william/**/target/allure-results/**
            com.login.william/**/target/surefire-reports/**
          if-no-files-found: warn

  api-tests:
    name: api-tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Testes de API (@api)
        run: mvn -q -B test -Dgroups=api
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-api
          path: |
            com.login.william/**/target/allure-results/**
            com.login.william/**/target/surefire-reports/**
          if-no-files-found: warn

  allure-report:
    name: allure-report
    runs-on: ubuntu-latest
    needs: [unit-tests, api-tests]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Unificar results
        run: |
          mkdir -p target/allure-results
          find artifacts -type d -name "allure-results" -exec cp -r {}/* target/allure-results/ \; || true
      - name: Gerar Allure
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: target/allure-results
          allure_report: target/allure-report
      - uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

  deploy-pages:
    name: deploy-pages
    runs-on: ubuntu-latest
    needs: allure-report
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./site
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
      - uses: actions/deploy-pages@v4
