name: CI - Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    # 👇 Faz todos os `run:` executarem em com.login.william
    defaults:
      run:
        working-directory: com.login.william

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Sanity check (onde está o pom?)
        run: |
          pwd
          ls -la
          test -f pom.xml && echo "Achei o pom.xml" || (echo "Sem pom.xml aqui" && exit 1)

      - name: Build & Test
        run: mvn -B -DskipTests=false clean verify

      - name: Package (artefato)
        if: success()
        run: mvn -B -DskipTests package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: simple-auth-jar
          path: com.login.william/target/*.jar  # <- caminho relativo à raiz do repo
